In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
type(A)

numpy.ndarray

In [4]:
A.ndim

2

In [5]:
A.shape

(2, 2)

In [6]:
A.dtype

dtype('int64')

In [7]:
A[0]

array([1, 2])

In [8]:
A[1]

array([3, 4])

In [9]:
A[A>1]

array([2, 3, 4])

In [10]:
A

array([[1, 2],
       [3, 4]])

In [11]:
A.T

array([[1, 3],
       [2, 4]])

In [12]:
B = np.array([10, 100])

In [13]:
A * B

array([[ 10, 200],
       [ 30, 400]])

In [14]:
B.dot(B)

10100