In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
type(A)

numpy.ndarray

In [4]:
A.ndim

2

In [5]:
A.shape

(2, 2)

In [6]:
A.dtype

dtype('int64')

In [7]:
A[0]

array([1, 2])

In [8]:
A[1]

array([3, 4])

In [9]:
A[A>1]

array([2, 3, 4])

In [10]:
A

array([[1, 2],
       [3, 4]])

In [11]:
A.T

array([[1, 3],
       [2, 4]])

In [12]:
B = np.array([10, 100])

In [13]:
A * B

array([[ 10, 200],
       [ 30, 400]])

In [14]:
B.dot(B)

10100

In [2]:
import pandas as pd

s = pd.Series([0.0, 3.6, 2.0, 5.8, 4.2, 8.0])
s

0    0.0
1    3.6
2    2.0
3    5.8
4    4.2
5    8.0
dtype: float64

In [3]:
s.index = pd.Index([0.0, 1.2, 1.8, 3.0, 3.6, 4.8])
s.index.name = 'MY_IDX'
s

MY_IDX
0.0    0.0
1.2    3.6
1.8    2.0
3.0    5.8
3.6    4.2
4.8    8.0
dtype: float64

In [4]:
s.name = "MY_SERIES"
s

MY_IDX
0.0    0.0
1.2    3.6
1.8    2.0
3.0    5.8
3.6    4.2
4.8    8.0
Name: MY_SERIES, dtype: float64

In [5]:
s[5.9] = 5.5

In [6]:
s

MY_IDX
0.0    0.0
1.2    3.6
1.8    2.0
3.0    5.8
3.6    4.2
4.8    8.0
5.9    5.5
Name: MY_SERIES, dtype: float64

In [7]:
ser = pd.Series([6.7, 4.2], index=[6.8, 8.0])
s = s.append(ser)
s

/var/folders/50/6fyr8m8d3c11wvj8rtvg06wr0000gn/T/ipykernel_37987/1815225506.py:2: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  s = s.append(ser)


0.0    0.0
1.2    3.6
1.8    2.0
3.0    5.8
3.6    4.2
4.8    8.0
5.9    5.5
6.8    6.7
8.0    4.2
dtype: float64

In [9]:
s.loc[8.0]

4.2

In [11]:
s.iloc[-1]

4.2

In [12]:
s.values[:]

array([0. , 3.6, 2. , 5.8, 4.2, 8. , 5.5, 6.7, 4.2])

In [13]:
s.iloc[:]

0.0    0.0
1.2    3.6
1.8    2.0
3.0    5.8
3.6    4.2
4.8    8.0
5.9    5.5
6.8    6.7
8.0    4.2
dtype: float64

In [14]:
s.drop(8.0)

0.0    0.0
1.2    3.6
1.8    2.0
3.0    5.8
3.6    4.2
4.8    8.0
5.9    5.5
6.8    6.7
dtype: float64

In [15]:
s.describe()

count    9.000000
mean     4.444444
std      2.430078
min      0.000000
25%      3.600000
50%      4.200000
75%      5.800000
max      8.000000
dtype: float64

In [16]:
s.index.name = 'MY_IDX'
s.name = 'MY_SERICES'

import matplotlib.pyplot as plt
plt.title("ELLIOTT_WAVE")
plt.plot(s, 'bs--')
plt.xticks(s.index)
plt.yticks(s.values)

Fontconfig warning: ignoring UTF-8: not a valid region tag


([<matplotlib.axis.YTick at 0x7fb7b9f2eaf0>,
 [Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, ''),
  Text(0, 0, '')])

In [1]:
import pandas as pd


In [3]:
df = pd.DataFrame({'KOSPI':[1915, 1961, 2026, 2467, 2041], 'KOSDAQ':[542, 682, 631, 798, 675]})
df  

KOSPI  KOSDAQ
0   1915     542
1   1961     682
2   2026     631
3   2467     798
4   2041     675

In [4]:
df = pd.DataFrame({'KOSPI':[1915, 1961, 2026, 2467, 2041], 'KOSDAQ':[542, 682, 631, 798, 675]}, index=[2014, 2015, 2016, 2017, 2018])
df

KOSPI  KOSDAQ
2014   1915     542
2015   1961     682
2016   2026     631
2017   2467     798
2018   2041     675

In [5]:
df.describe()

KOSPI      KOSDAQ
count     5.000000    5.000000
mean   2082.000000  665.600000
std     221.117616   92.683871
min    1915.000000  542.000000
25%    1961.000000  631.000000
50%    2026.000000  675.000000
75%    2041.000000  682.000000
max    2467.000000  798.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 2014 to 2018
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   KOSPI   5 non-null      int64
 1   KOSDAQ  5 non-null      int64
dtypes: int64(2)
memory usage: 120.0 bytes


In [7]:
kospi = pd.Series([1915, 1961, 2026, 2467, 2041], index=[2014, 2015, 2016, 2017, 2018], name='KOSPI')
kospi

2014    1915
2015    1961
2016    2026
2017    2467
2018    2041
Name: KOSPI, dtype: int64

In [8]:
kosdaq = pd.Series([542, 682, 631, 798, 675], index=[2014, 2015, 2016, 2017, 2018], name='KOSDAQ')
kosdaq

2014    542
2015    682
2016    631
2017    798
2018    675
Name: KOSDAQ, dtype: int64

In [9]:
df = pd.DataFrame(
    {kospi.name: kospi, kosdaq.name: kosdaq}
)

In [10]:
df

KOSPI  KOSDAQ
2014   1915     542
2015   1961     682
2016   2026     631
2017   2467     798
2018   2041     675

In [11]:
columns = ['KOSPI', 'KOSDAQ']
index = [2014, 2015, 2016, 2017, 2018]
rows = []
rows.append([1915, 542])
rows.append([1961, 682])
rows.append([2026, 631])
rows.append([2467, 798])
rows.append([2041, 675])
df = pd.DataFrame(rows, columns=columns, index=index)
df

KOSPI  KOSDAQ
2014   1915     542
2015   1961     682
2016   2026     631
2017   2467     798
2018   2041     675

In [12]:
for i in df.index:
    print(i, df['KOSPI'][i], df['KOSDAQ'][i])
    

2014 1915 542
2015 1961 682
2016 2026 631
2017 2467 798
2018 2041 675
